call yarn remove react-native-vector-icons
call yarn remove react-native-camera
call yarn remove react-native-elements
call yarn remove react-native-gesture-handler
call yarn remove react-native-reanimated
call yarn remove react-native-router-flux
call yarn remove react-native-navbar
call yarn remove react-native-screens
call yarn remove react-native-sound
call yarn remove simple-line-icons